gomuks/gomuks

README.md
ui/fuzzy-view.go
ui/view-main.go

Everything appears to be functional.  Still need to figure out how to get transparency working.

fuzzy search prototype

---

ui/tag-room-list.go

fix room name overwriting unread count

---

README.md

A small update to switch out some links and added the `/create` command to the list of commands at the bottom.

Readme Update.

---

config/config.go
ui/view-main.go

There should maybe be a `notify_message` option as well.

add notify_sound config option

---

README.md

Took me a bit of spelunking through the code to work out how to view images so figured it was worth adding to the README.

Note mouse behaviour in README

---

ui/room-view.go

hjkl keybinds for selection

---

go.mod
go.sum
ui/command-processor.go
ui/commands.go
ui/room-view.go

github.com/atotto/clipboard
I have no experience in go and not much in git. I nevertheless hope this is more useful than opening an issue about clipboard support.

Implement copying to clipboard

---

go.mod
go.sum
ui/commands.go
ui/help-modal.go

I'm quite sure that setting `hm.Component = mauview.Center(hm.container, width, height)` in Draw could be done in a more appropriate way.

Add help popup

---

lib/open/open.go
ui/message-view.go
ui/room-view.go

Fixes zombie processes left from opening files

reap children on /open

---

ui/autocomplete.go
ui/command-processor.go

Add command autocompletion for toggle

---

debug/debug.go

Closes: #307
Tested this patch by applying on top of gomuks 0.3.0

Make debug dir specific to username to ease off multi user logins

---

web/src/ui/emojipicker/EmojiPicker.css

web/emojipicker: don't stretch emoji in big preview

---

pkg/hicli/html.go
pkg/hicli/sync.go
web/src/index.css
web/src/ui/timeline/content/index.css

web/css: highlight inline code

---

.github/workflows/go.yml

ci: fix Go lint task

---

.envrc
flake.lock
flake.nix

flake: add devenv for Nix

---

web/src/ui/roomlist/RoomList.css
web/src/ui/roomview/RoomView.css
web/src/ui/roomview/RoomViewHeader.css
web/src/ui/roomview/RoomViewHeader.tsx
web/src/ui/settings/SettingsView.css
web/src/ui/settings/SettingsView.tsx

web/roomview: render room topic in header

---

.pre-commit-eslint.sh
.pre-commit-tsc.sh

pre-commit: use full relative path to eslint and tsc

---

web/src/ui/composer/Autocompleter.css

apparently this one didn't fix all the cases of that in #470

web/emoji: fix streched images in shortcodes

---

web/src/api/media.ts
web/src/api/types/mxtypes.ts
web/src/ui/timeline/ReplyBody.css
web/src/ui/timeline/ReplyBody.tsx
web/src/ui/timeline/TimelineEvent.css
web/src/ui/timeline/TimelineEvent.tsx
web/src/ui/timeline/content/index.ts

Closes #480 
Implements [MSC4144: Per-message profiles](https://github.com/matrix-org/matrix-spec-proposals/pull/4144)

Render MSC4144 Per-Message Profiles

---

web/src/ui/timeline/TimelineEvent.tsx

web/timeline: disable right click context menu on videos

---

web/src/index.css
web/src/ui/timeline/TimelineEvent.css

web/timeline: add variable for vertical padding

---

web/src/ui/modal/Lightbox.css

web/lightbox: fix scrollbars

---

web/src/api/types/mxtypes.ts
web/src/ui/composer/MessageComposer.css
web/src/ui/composer/MessageComposer.tsx
web/src/ui/timeline/content/RoomTombstoneBody.tsx
web/src/ui/timeline/content/index.ts

web/{timeline,composer}: render `m.room.tombstone` events

---

web/src/ui/settings/SettingsView.tsx

settings: add button to go to predecessor room

---

web/src/ui/timeline/content/ACLBody.tsx

web/timeline: render ACL changes in details tag

---

pkg/hicli/json-commands.go
pkg/hicli/jsoncmd/params.go
web/src/api/rpc.ts
web/src/ui/rightpanel/UserModeration.tsx

technically you can also use MSC4293 with kicks too but mautrix-go doesnt implement that so i dont care

web/rightpanel: Support using MSC4293 alongside mass redacts
