- ui/fuzzy-search-modal.go
This option causes issues for room titles like `[Discord] Foobar Room`.  It doesn't seem like it was being used anyway.
> turn off dynamic colors in fuzzy search

- ui/commands.go
- ui/view-main.go
In some cases tcell sends Key{Ctrl,Alt}{Up,Down} events instead of
Key{Up,Down} event that have the corresponding modifier mask set.
(these key combinations are used for switching rooms)
> Add support for more key events

- README.md
Hey all!
The README provides a good overview of the some functions and commands that gomuks can interpret.
However commands are invoked by a leading slash prior to the command. That got me confused, because I didn't look into the wiki directly.
I suggest printing the slash in front of commands in the README as well, so that CLI tool newbies like me don't get confused. I guess slashes are the standard operator for invoking options. I remember that profanity and other tools did this as well. My bad.
What do you think?
Regards
Patrik
> Clarifying the README.md

- ui/room-list.go
- ui/tag-room-list.go
- ui/view-main.go
Alt-a is "standard" in irssi & weechat to jump to next channel with activity. This implement basic functionality for it. Does not sort by priority yet but seems to work.
> Alt-a to jump to next channel with unread messages.

- matrix/matrix.go
- ui/command-processor.go
- ui/commands.go
Added the ability to create a room from within gomuks using the now
`/create` command. This command takes the room name followed by the
alias. Room name may contain spaces but the alias may not as per the
Matrix alias conventions.
Also updated `/help` in `ui/command-processor.go` to include the new command.
Added the needed `CreateRoom` func to `matrix/matrix.go`
This should satisfy issue #5.
> Users can now create a new room directly in Gomuks

- ui/messages/imagemessage.go
Using the "image" package from the standard library the images loaded by gomuks now scale to one third the size of the text area.
The image data contains both hight and width while the scaling uses only width the option to scale by hight is possible if passed into `CalculateBuffer()`. `ansimage.NewScaledFromReader()` now takes the new variable based off the size of the buffers' width.
This may resolve issue #92
> Scale image message based on the user's text area.

- ui/room-view.go
The crash happens sometimes when selecting media to download. The crash happens when ok is false.
Here is a stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xae194b]
goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
/home//git/gomuks/debug/debug.go:109 +0x94
panic(0xb5fe00, 0x1374300)
/usr/lib/go/src/runtime/panic.go:969 +0x166
maunium.net/go/mauview.(*Application).Start.func1(0xc0003b9200)
/home//go/pkg/mod/maunium.net/go/mauview@v0.1.1/application.go:99 +0x82
panic(0xb5fe00, 0x1374300) …
```
> Fix crash when using /o command

- ui/command-processor.go
https://github.com/tulir/gomuks/blob/286c6fce01e12779c4f2dd1bbeda86f1029fa49e/ui/command-processor.go#L225
This `true` should be replaced with `ok`. If following line fails, we wouldn't have any completions at all
https://github.com/tulir/gomuks/blob/286c6fce01e12779c4f2dd1bbeda86f1029fa49e/ui/command-processor.go#L217
> Fix command autocompletion

- ui/fuzzy-search-modal.go
`fs.selected` does not get reset to 0 when the search text is cleared, which causes the wrong room to be selected or an index error.
Steps to reproduce:
1. Open fuzzy search and enter a search term which return many matching rooms.
2. Hit tab N times. (`fs.selected` == N)
3. Clear the search text without selecting a room and enter search term which returns 1 matching room.
4. `fs.selected` is still N even though there is only 1 result.  Hit enter to get an exception.
```
[evan@blackbox gomuks] gomuks 
panic: runtime error: index out of range [1] with length 1 [recovered]
panic: runtime error: index out of range [1] with length 1 [recovered]
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover() …
```
> fix index error in fuzzy search

- ui/commands.go
That means direct as in direct messaging.
See also:
- https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-createroom
- https://matrix.org/docs/spec/client_server/latest#module-dm
- https://godoc.org/maunium.net/go/mautrix#ReqCreateRoom
fixes #259
> Mark private chat as direct

- config/config.go
- ui/commands.go
- ui/room-view.go
This adds an option to use <Enter> to create a new line, and <Alt+Enter> to send a message, essentially swapping <Enter> and <Alt+Enter>.
This allows users to compose multi-line messages easily and also allow pasting multi-line messages from the clipboard.
> Add NewLineByDefault toggle

- ui/fuzzy-search-modal.go
- ui/help-modal.go
- ui/member-list.go
- ui/room-list.go
- ui/room-view.go
- ui/verification-modal.go
This is not the configurable colors change as was requested in issue #23 but at least it makes gomuks usable with black on white terminal color schemes, and should not impact white on black looks significantly.
There's at least still an issue with /help box's title as boxes in mauview don't have ForegroundColor property.
> ui: use ColorDefault where appropriate

- lib/notification/notify_openbsd.go
I use `gomuks` on a laptop running OpenBSD with `notify-send`, but I noticed that the SendNotification function was using the `lib/notification/notify_unsupported.go` library instead of the `lib/notification/notify_linux.go` library, which should work fine for OpenBSD, minus the reliance on `paplay`, which is not available in base on OpenBSD.
I created `lib/notification/notify_openbsd.go` using `notify_linux.go` as a template. It's the same thing, essentially, minus any notification sounds since OpenBSD has no way to play .ogg files in base and I don't want to create extra dependencies.
> Added notify_openbsd.go to the notification library so that notifications will be available on OpenBSD systems as well

- config/config.go
- ui/commands.go
- ui/message-view.go
This adds a toggle so timestamps in message rooms can be hidden
Screenshot with timestamps disabled:
> Add toggle for timestamps

- config/config.go
- go.mod
- go.sum
- keybindings.sample.yaml
- ui/fuzzy-search-modal.go
- ui/help-modal.go
- ui/room-view.go
- ui/verification-modal.go
- ui/view-main.go
By default no shortcuts are mapped.
Previous mappings included as sample (except `q` no longer closes modal)
Consider as alternative to #325
> Configurable key shortcuts

- ui/room-view.go
Copy-pasted the extract from `SendMessageHTML` that does the same thing. **This patch has not been tested yet** as I do not have a Go development environment accessible currently. I will do so in the upcoming days.
My doubts would be about whether this transformation should come before or after the debug printing. Any opinions?
Thanks for gomuks, it has been really enjoyable to use!
> Allow emojis in reactions

- ui/messages/html/parser.go
The TextColor is also set to make sure it is readable with black on white themes.
Fixes #134
> Display inline code in messages

- ui/messages/html/parser.go
New lines were not displayed in plain text messages. There might be a better way, but I choose to manually convert the newline characters into BreakEntities inside of a ContainerEntity.
I didn't use my new function for the value of a plan text link, as it must not contain any new lines.
```json
{
"room_id": "!***:matrix.org",
"type": "m.room.message",
"content": {
"org.matrix.msc1767.text": "Probablement que j'ai pas répondu alors 😅\nMerci pour le partage mais je suis pas chaud pour y aller",
"body": "Probablement que j'ai pas répondu alors 😅\nMerci pour le partage mais je suis pas chaud pour y aller",
"msgtype": "m.text"
}
}
```
> Preserve newlines in plain text messages

- ui/messages/html/parser.go
Because some tokens can contain newlines and not only comment tokens, I removed the comments specific code to handle newlines in a more generic way.
Fixes #274
Fixes #213
> Fix mangled newlines in some code blocks

- ui/messages/html/parser.go
This fixes an incorrect rendering behaviour in the timeline and the plaintext mode, introduced by #388, for plain text only messages that combined URLs and newlines.
For example with events of this kind:
```json
{
"type": "m.room.message",
"content": {
"body": "Test message :\n\nhttps://alink.com/that/is/longer\nhttps://ashortlink.fr\n\nEnd of message",
"msgtype": "m.text"
}
}
```
This changes makes sure that there is always only one container and no empty text Entities in the HTML message.
**Timeline Before**
**Timeline After**
**Plaintext Before**
**Plaintext After**
I am sorry for not catching this bug earlier.
This time I tried to test a lot of edge cases and it behaved properly.
> Fix line breaks with URLs in plaintext only messages

- debug/debug.go
- main.go
Closes: #429
This PR does two things:
* Change log dir to ~/.local/state if `XDG_STATE_HOME` is unset which is as per the freedesktop guidelines
* Disables logging by default
+ Gomuks keeps logging events, and the size of the debug log can quickly shoot up if there are any crashes. Unless the user wants, it is not a good idea to keep dumping logs by default. However, logging would work just fine if `DEBUG=1` is passed.
Tested this on top of 0.3.0 gomuks release.
> Fix debug dir on linux and disable logging by default

- cmd/gomuks/main.go
- pkg/gomuks/gomuks.go
- pkg/gomuks/server.go
makes using the library without the web bits easier
> cmd/gomuks: move web package from pkg/gomuks

- build.sh
Use `/usr/bin/env bash` instead of `/bin/bash` to make the build script work on NixOS.
> build: user /usr/bin/env

- web/src/index.css
This is a minor fix, mainly for the scrollbar on chrome+windows+dark mode.
Before:
After
> web/css: set css color-scheme property to match theme

- web/src/ui/roomlist/RoomList.css
Fixes #540
Padding in both inline and block directions is configurable with the respective `unread-count-padding` CSS variables - if you'd prefer, I can move these to `index.css` / `:root` for easier overrides.
> web/roomlist: prevent overflow in unread counters

- web/src/ui/timeline/TimelineEvent.tsx
I'm not sure if it's intentional, but right now if you delete a message that was a reply to another message, the reply is still rendered:
I think it's weird, so this PR makes it so that it just looks like a deleted message with no info about the replied-to message:
> web/timeline: don't show replied-to message if message is redacted

- web/src/ui/util/TooltipButton.css
Currently it is harcoded to `#fff` which breaks dark mode:
Changes:
> web/util: Change the tooltip background color to --background-color

- pkg/hicli/sync.go
- web/src/api/types/mxtypes.ts
- web/src/api/types/preferences/preferences.ts
- web/src/ui/timeline/TimelineEvent.tsx
- web/src/ui/timeline/URLPreviews.css
- web/src/ui/timeline/URLPreviews.tsx
Related to #479
Sending will come in a separate PR
Screenshots:
A single preview:
Renders multiple side-by-side and it is scrollable:
> Render MSC4095 bundled URL previews

- web/src/api/types/mxtypes.ts
- web/src/ui/MainScreen.tsx
- web/src/ui/timeline/content/PolicyRuleBody.tsx
- web/src/ui/timeline/content/index.ts
This PR simply adds a display for m.policy.rule.user, m.policy.rule.room, and m.policy.rule.server, similar to how m.room.server_acl is handled.
Demo:
This display only affects policy list rooms, such as https://matrix.to/#/#cme:nexy7574.co.uk.
> Add a display for m.policy.rule.{user,room,server}

- web/src/ui/composer/MessageComposer.tsx
We already are setting the button to disabled, but you can also invoke
onClickSend by pressing "Enter". See
https://github.com/tulir/gomuks/blob/b01b3f0e32d354c45df4159da05f3bb4ca029d61/web/src/ui/composer/MessageComposer.tsx#L615
> web/composer: prevent sending when loading media

- web/src/ui/timeline/URLPreviews.css
- web/src/ui/timeline/URLPreviews.tsx
> timeline: don't render empty url-previews div

- web/src/api/statestore/main.ts
- web/src/api/types/mxtypes.ts
Add room type "org.matrix.msc3417.call" to the list of known rooms that are displayed in the room list.
Untested because I cannot easily compile now, but trivial patch (famous last words)
> web/statestore: don't hide video rooms

- web/src/ui/timeline/content/LocationMessageBody.tsx
Just some basic validation on geo: URIs that is currently lacking.
> web/timeline: dont allow extreme/illegal values in geo URIs

- web/src/ui/roomview/RoomPreview.css
Limits the height of the room name to 6rem and provides a y-scroll for names that exceed the height limit. Prevents invited rooms hiding the reject button
> web/roomview: prevent room name overflowing the room invite view

- pkg/gomuks/media.go
Renaming (aka moving) a temporary file evidently does not seem to work on Windows when there is an open filehandle. This leads to all user and space avatars remaining blank as temporary files could not be moved to the cache. Simply closing the file before moving should make Windows behave (Linux had always just worked)
> Def*ck Windows (make moving temporary files work)
